# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3ebd12a227be52f661ee27282c9e45d7a4d85631f606e854c629ef8a7772021daeb702a5030802491c1872ced7a106513d1e67eb0b65ed5b2905788ddc8c30be

test:
  secret_key_base: feacb698349b22a42b845cf1bd1282c68e109df7efb20d148acbdc2a72d5a7e1756f57fc31a38aae36a23b32958ed55b0108463027800dc867e39b0b5bb1d100

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 4b87c3cf120388edadf95c9c19195df1d4aa69bfd4b679979150b08d5f619b5a0e56a79a36da1f3153df05c7f5fda7191a1be26330d7ad6b641705edab57d57a
